### ISSUE TITLE
Builder tries to include file from github when present in path

### ISSUE THREAD

**Issue by NasibMansour** [electricimp/Builder#68] opened 2019-05-03 19:20 UTC
When a file is included with the word `github` in it, builder tries to include that file from GitHub.

For example, if one of the files has the following include:  
`@include "./dir/GitHub/lib/file.nut"` 

Builder will fail because it'll try to get that file from GitHub rather than the local machine.

**Comment by alexey-nbl** [comment] 2019-05-03 20:22
Does it happen even when the new option (--use-remote-relative-includes) is not set?
We will have a look.

**Comment by ppetrosh** [comment] 2019-05-04 13:11
@NasibMansour can you please provide a minimised code sample that helps to reproduce the issue?

**Comment by NasibMansour** [comment] 2019-05-06 14:15
I found a simpler way to reproduce the issue.

Suppose I have a file called `file1.nut` in a directory 'Desktop/GitHub/files/tests` and I try to do:
`pleasebuild Desktop/GitHub/files/tests/file1.nut` then I'll get the following error message:

`Failed to get source "Desktop/GitHub/files/tests/file1.nut" from GitHub: Not Found (main:1)`

Important thing I found while trying to reproduce the issue: It only happens when the file is included two levels after GitHub so for example if the file was one level up and I do:

`pleasebuild Desktop/GitHub/files/file1.nut` then it'll work just fine.

I thought this was worth noting

**Comment by FedorUporov** [comment] 2019-05-06 19:11
@NasibMansour, thank you a lot for detailed description.
Now it has become possible to find the cause of the issue and it will be fixed soon.
Looks like, it does not related with new option (--use-remote-relative-includes).

**Comment by betzrhodes** [comment] 2019-05-23 23:13
This is fixed in release v2.8.1 and is now available.

**Closed** 2019-05-23 23:14 UTC
